ButtonState/Models/ButtonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ButtonState.Models
{
    public class ButtonModel
    {
        public int State { get; set; }

        public ButtonModel(int state)
        {
            State = state;
        }
    }
}

ButtonState/Controllers/ButtonController.cs
using ButtonState.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ButtonState.Controllers
{
    public class ButtonController : Controller
    {
        static List<ButtonModel> buttons = new List<ButtonModel>();
        Random ran = new Random();

        // GET: Button
        public ActionResult Index()
        {
            for(int i=0; i<25; i++)
            {
                if (ran.Next(10) > 5)
                    buttons.Add(new ButtonModel(1));
                else if (ran.Next(10) > 5)
                {
                    buttons.Add(new ButtonModel(2));
                }
                else
                {
                    buttons.Add(new ButtonModel(3));
                }
                   
            }
            return View("Index", buttons);
        }

        public ActionResult HandleButtonClick(string mine)
        {
            int buttonNumber = Int32.Parse(mine);
            if (buttons[buttonNumber].State == 1)
            {
                buttons[buttonNumber].State = 2;
            }
            else if (buttons[buttonNumber].State == 2)
            {
                buttons[buttonNumber].State = 3;
            }
            else
            {
                buttons[buttonNumber].State = 1;
            }

            return View("Index", buttons);
        }
    }
}

ButtonState/Views/Button/Index.cshtml
@model List<ButtonState.Models.ButtonModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @Html.Label("Playing with balls")
        @using (Html.BeginForm("HandleButtonClick", "Button"))
        {
            for (int i = 0; i < Model.Count; i++)
            {
                if (i % 5 == 0)
                {
                    <br />
                }
    <button type="submit" name="mine" value="@i">
        @if (Model[i].State == 1)
        {
            <img src="~/Images/gold.jpg" />

        }

        else if (Model[i].State == 2)
        {
            <img src="~/Images/on.png" />
        }
        
        else
        {
            <img src="~/Images/tennis.png" />
        }


    </button>

            }
        }



    </div>
</body>
</html>